# Generated by Django 4.0 on 2021-12-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloPost', models.TextField(max_length=100)),
                ('post', models.TextField(max_length=10000)),
            ],
        ),
    ]
